kind: Service
apiVersion: v1
metadata:
  name: deleteuser
  namespace: default
spec:
  selector:
    app: deleteuser
  type: ClusterIP
  ports:
    - name: deleteuser-port
      port: 5001
      targetPort: 5001
