apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - createuser-k/
  - deleteuser-k/
  - getuser-k/
  - mysqldb-k/
# kustomization.yaml

namespace: default
nameSuffix: -prd
commonLabels:
  env: prod-app
commonAnnotations:
  branch: prod-app
images:
  - name: adesh0303/flaskapp
    newTag: latest
