apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysqldb # has to match .spec.template.metadata.labels
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: mysqldb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mysqldb
        image: adesh0303/eks-app:mysqldb
        volumeMounts:
        - name: db-data
          mountPath: var/lib/mysqldb
      tolerations:
        - key: "userapp"
          operator: "Equal"
          effect: "NoSchedule"
          value: "critical"
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi