apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysqldb # has to match .spec.template.metadata.labels
  serviceName: "mysqldb"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: mysqldb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysqldb
          image: adesh0303/eks-app:mysqldb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: rootpass
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: databasename
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: userpass
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysqldb
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: mysql-pv-claim
