apiVersion: apps/v1
kind: Deployment
metadata:
  name: createuser-deploy #>Charts.name
  namespace: default
  labels:
    app: createuser #charts.createuserlabels
spec:
  replicas: 1 #.values.replicaCount
  selector:
    matchLabels:
      app: createuser #Charts.createuserlables
  template:
    metadata:
      labels:
        app: createuser #Charts.createuserlables
    spec:
      containers:
        - name: pyapp #.Chart.Name
          image: adesh0303/flaskapp:createuser-eks #.Values.image.repository:.Values.images.tag
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbhost
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbpass
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbuser
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbport
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbname
