apiVersion: v1
kind: ConfigMap
metadata:
  name: pyapp-config
  labels:
    config: appspecs
data:
  rootpass: "root"
  databasename: "userdb"
  username: "myuser"
  userpass: "mypass"
  dbhost: "mysqldb"
  dbport: "3306"
  dbname: "userdb"
  dbuser: "myuser"
  dbpass: "mypass"
