apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: default
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: adesh0303/eks-app:mysqldb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: rootpass
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: databasename
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: userpass
