apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deleteuser-deploy.yaml
  - deleteuser-service.yaml
# kustomization.yaml

images:
  - name: adesh0303/deleteuser-service
    newTag: v0
