apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deploy.yaml
  - frontend-service.yaml
# kustomization.yaml

images:
  - name: adesh0303/nginx-frontend
    newTag: v0
