kind: Service
apiVersion: v1
metadata:
  name: createuser
  namespace: default
spec:
  selector:
    app: createuser
  type: NodePort
  ports:
    - name: createuser-port
      port: 80
      targetPort: 80
