apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# kustomization.yaml
resources:
- createuser-deploy.yaml
- createuser-service.yaml
images:
- name: adesh0303/eks-app
  newTag: 93161a9869729ad6b6c9120388104a968f89761a
