apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# kustomization.yaml
resources:
- createuser-deploy.yaml
- createuser-service.yaml
images:
- name: adesh0303/eks-app
  newTag: a068111f437c0373ee9e8f695ca7dc6fce118870
