apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - getuser-deploy.yaml
  - getuser-service.yaml
# kustomization.yaml

images:
  - name: adesh0303/eks-app
    newTag: getuserservice
