apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- getuser-deploy.yaml
- getuser-service.yaml
# kustomization.yaml

images:
- name: adesh0303/eks-app
  newTag: b945dff7979317348831c7a612174de82c9e035b
