name: getuservice CI

on:
  push:
    paths:
      - src/backend/getuser/**
  pull_request:
    paths:
      - src/backend/getuser/**

permissions:
  contents: write

jobs:
  build-phase:
    uses: ./.github/workflows/image-builder.yml
    with:
      image_repo: adesh0303/eks-app
      dockerfile_path: src/backend/getuser/
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  kustomize:
    needs: build-phase
    uses: ./.github/workflows/update-kustomize.yml
    with:
      service_name: getuservice
      image_repo: adesh0303/eks-app
      kustomize_path: k8s/getuser
