name: image-builder

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "Name of the service (optional)"
        required: false
        default: ""
      dockerfile_path:
        description: "Path to the Dockerfile"
        required: true
        default: ""
      image_repo:
        description: "Docker image repository"
        required: true
        default: ""
      username:
        description: "Docker Hub username"
        required: true
        default: ""
      password:
        description: "Docker Hub password"
        required: true
        default: ""
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository UserPortal ðŸŸ 
        uses: actions/checkout@v4

      - name: Set up Docker Buildx ðŸŸ 
        uses: docker/setup-buildx-action@v2

      - name: Check Docker version
        run: if docker --version; then echo "Docker is installed âœ…"; else echo "Docker is not installed"; exit 1; fi

      - name: Log in to Docker Hub ðŸŸ 
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Build and push Docker image ðŸ”ƒ
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ inputs.image_repo }}:${{ github.sha }}

      - name: Output image details ðŸŸ 
        run: |
          echo "âœ…Docker image ${{ inputs.image_repo }}:${{ github.sha }} built and pushed successfully."
