name: image-builder

# This is reusable workflow to build Docker images and push to Docker Hub
#This workflow called bu other service-specific workflows
#Required inputs as below:
# image_repo: Full image repository name (e.g. adesh0303/<repo-name>)
# dockerfile_path: Path to the Dockerfile directory

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        description: "Docker Hub username"
        required: true
      DOCKER_PASSWORD:
        description: "Docker Hub password"
        required: true
    inputs:
      image_repo:
        description: "Full image repo (e.g. my-registry/get-user)"
        required: true
        type: string
      dockerfile_path:
        description: "Path to Dockerfile directory"
        required: true
        type: string
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository UserPortal ðŸŸ 
        uses: actions/checkout@v4

      - name: Set up Docker Buildx ðŸŸ 
        uses: docker/setup-buildx-action@v2

      - name: Check Docker version
        run: if docker --version; then echo "Docker is installed âœ…"; else echo "Docker is not installed"; exit 1; fi

      - name: Log in to Docker Hub ðŸŸ 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image ðŸ”ƒ
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ inputs.image_repo }}:${{ github.sha }}

      - name: Output image details ðŸŸ 
        run: |
          echo "âœ…Docker image ${{ inputs.image_repo }}:${{ github.sha }} built and pushed successfully."
