name: Update Kustomize Image

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "Service name (e.g. get-user)"
        required: true
        default: ""
      image_repo:
        description: "Full image repo (e.g. my-registry/get-user)"
        required: true
        default: ""
      kustomize_path:
        description: "Path to kustomization directory"
        required: true
        default: ""
  # workflow_call:
  #   inputs:
  #     service_name:
  #       description: "Service name (e.g. get-user)"
  #       required: true
  #       type: string
  #     image_repo:
  #       description: "Full image repo (e.g. my-registry/get-user)"
  #       required: true
  #       type: string
  #     kustomize_path:
  #       description: "Path to kustomization directory"
  #       required: true
  #       type: string
jobs:
  update-kustomize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update image tag in kustomization.yaml
        run: |
          cd ${{ inputs.kustomize_path }}
          kustomize edit set image \
            ${{ inputs.image_repo }}=*:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy: update ${{ inputs.service_name }} image to ${{ github.sha }}"
          git push
