name: Update Kustomize Image

# This is a reusable workflow to update kustomization.yaml with new image tag
# This workflow is called by other service-specific workflows
# Required inputs as below:
# service_name: Name of the service (e.g. get-user)
# image_repo: Full image repository name (e.g. adesh0303/<repo-name>)
# kustomize_path: Path to the kustomization directory

on:
  workflow_call:
    inputs:
      service_name:
        description: "Service name (e.g. get-user)"
        required: true
        type: string
      image_repo:
        description: "Full image repo (e.g. my-registry/get-user)"
        required: true
        type: string
      kustomize_path:
        description: "Path to kustomization directory"
        required: true
        type: string

permissions:
  contents: write

jobs:
  tag-updater:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update image tag in k8s/kustomization.yaml ðŸŸ¢
        run: |
          cd ${{ inputs.kustomize_path }}
          kustomize edit set image \
            ${{ inputs.image_repo }}=*:${{ github.sha }}

      - name: Commit and push changes âœ…
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy: update ${{ inputs.service_name }} image to ${{ github.sha }}"
          git push
